config/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('todo/', include('todo.urls')),
]

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('vonly/', views.TodoVueOnlyTV.as_view(), name='vonly'),
    path('create/', views.TodoCV.as_view(), name='create'),
    path('list/', views.TodoLV.as_view(), name='list'),
    path('<int:pk>/delete/', views.TodoDelV.as_view(), name='delete'),
    path('mixin/', views.TodoMOMCV.as_view(), name='mixin'),
    path('<int:pk>/delete2/', views.TodoDelV2.as_view(), name='delete2'),
]

todo/models.py
from django.db import models


# Create your models here.
class Todo(models.Model):
    name = models.CharField('NAME', max_length=5, blank=True)
    todo = models.CharField('TODO', max_length=50)

    def __str__(self):
        return self.todo

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.name:
            self.name = "홍길동"
        super().save()

config/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

todo/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DeleteView
from django.views.generic.list import MultipleObjectMixin

# Create your views here.
from todo.models import Todo


class TodoVueOnlyTV(TemplateView):
    template_name = 'todo/todo_vue_only.html'


class TodoCV(CreateView):
    model = Todo
    fields = '__all__'
    template_name = 'todo/todo_form.html'
    success_url = reverse_lazy('todo:list')


class TodoLV(ListView):
    model = Todo
    template_name = 'todo/todo_list.html'


class TodoDelV(DeleteView):
    model = Todo
    template_name = 'todo/todo_confirm_delete.html'
    success_url = reverse_lazy('todo:list')


class TodoDelV2(DeleteView):
    model = Todo
    # template_name = 'todo/todo_confirm_delete.html'
    success_url = reverse_lazy('todo:mixin')

    def get(self, request, *args, **kwargs):
        return self.delete(self, request, *args, **kwargs)


class TodoMOMCV(MultipleObjectMixin, CreateView):
    model = Todo
    fields = '__all__'
    template_name = 'todo/todo_form_list.html'
    success_url = reverse_lazy('todo:mixin')

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        return super().post(request, *args, **kwargs)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}home.html{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    {% block extra-style %}{% endblock %}

</head>
<body style="padding-top: 90px;">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Vue-Django System</span>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item mx-1 btn btn-primary">
        <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item mx-1 btn btn-primary">
        <a class="nav-link text-white" href="{% url 'todo:vonly' %}">VueOnly</a>
      </li>
      <li class="nav-item mx-1 btn btn-primary">
        <a class="nav-link text-white" href="{% url 'todo:create' %}">DjangoOnly</a>
      </li>
      <li class="nav-item mx-1 btn btn-primary">
        <a class="nav-link text-white" href="{% url 'todo:mixin' %}">DjangoMixin</a>
      </li>

      <li class="nav-item dropdown mx-1 btn btn-primary">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Util
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
    </ul>

    <form class="form-inline my-2">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
    </form>

    <ul class="navbar-nav ml-5 mr-5">
      <li class="nav-item dropdown mx-1 btn btn-primary">
        <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">
          <i class="fas fa-user"></i>&nbsp; Anonymous &nbsp;
        </a>
        <div class="dropdown-menu">
          <a href="{% url 'home' %}" class="dropdown-item">Login</a>
          <a href="{% url 'home' %}" class="dropdown-item">Register</a>
        </div>
      </li>
    </ul>

  </div>
</nav>

<div class="container">
  {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script src="https://kit.fontawesome.com/0a42d77ee4.js" crossorigin="anonymous"></script>

{% block extra-script %}{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

templates/todo/todo_confirm_delete.html
{% extends 'base.html' %}

{% block title %}todo_confirm_delete.html{% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 70px;
            padding-left: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="app">

        <h1>Todo Delete</h1>
        <p>Are you sure to delete {{ object }} ?</p>
        <br>

        <form action="." method="post"> {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-sm">Confirm</button>
        </form>

    </div>
{% endblock %}

templates/todo/todo_form.html
{% extends 'base.html' %}

{% block title %}todo_form.html{% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 90px;
            padding-left: 20px;
            line-height: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
            line-height: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="app">
        <h1>My Todo App !</h1>
        <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
        <br>
        <br>

        <form action="." class="inputBox" method="post"> {% csrf_token %}
            <input class="name" type="text" placeholder="name ..." name="name">
            <input class="item" type="text" placeholder="type anything welcomed ..." name="todo">
            <button type="submit" class="btn btn-info btn-sm">ADD</button>
        </form>
    </div>
{% endblock %}

templates/todo/todo_form_list.html
{% extends 'base.html' %}

{% block title %}todo_form.html{% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 90px;
            padding-left: 20px;
            line-height: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
            line-height: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
        .removeBtn:hover {
            color: red;
        }
        .modal-footer a {
            color: white;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="app">
        <h1>My Todo App !</h1>
        <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
        <br>
        <br>

        <form action="." class="inputBox" method="post"> {% csrf_token %}
            <input class="name" type="text" placeholder="name ..." name="name">
            <input class="item" type="text" placeholder="type anything welcomed ..." name="todo">
            <button type="submit" class="btn btn-info btn-sm">ADD</button>
        </form>

        <ul class="todoList">
            {% for todo in object_list %}
            <li>
                <span>{{ todo.name }}::: {{ todo.todo }} </span>
                <span class="removeBtn" data-toggle="modal" data-target="#myModal"
                      data-id="{{todo.id}}" data-name="{{todo.name}}" data-todo="{{todo.todo}}">&#x00D7</span>
            </li>
            {% endfor %}
        </ul>
    </div>

<div class="modal" id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Are you sure to delete ?</h5>
      </div>
      <div class="modal-body">
          body-text
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger"><a href="">Delete</a></button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra-script %}
<script>
$('#myModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget)
  var id = button.data('id')
  var name = button.data('name')
  var todo = button.data('todo')

  var modal = $(this)
  modal.find('.modal-body').text(name + '::: ' + todo)
  modal.find('.modal-footer a').attr('href', '/todo/' +id + '/delete2/')
})
</script>
{% endblock %}

templates/todo/todo_list.html
{% extends 'base.html' %}

{% block title %}todo_list.html{% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 70px;
            padding-left: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="app">

        <h1>My Todo App !</h1>
        <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
        <br>
        <br>
        <ul class="todoList">
            {% for todo in object_list %}
            <li>
                <span>{{ todo.name }}::: {{ todo.todo }} </span>
                <span class="removeBtn"><a href="{% url 'todo:delete' todo.id %}">&#x00D7</a></span>
            </li>
            {% endfor %}
        </ul>

    </div>
{% endblock %}

templates/todo/todo_vue_only.html
{% extends 'base.html' %}

{% block title %}todo_vue_only.html{% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 90px;
            padding-left: 20px;
            line-height: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
            line-height: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="app" v-cloak>

        <h1>My Todo App !</h1>
        <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
        <br>
        <br>

        <div class="inputBox">
            <input class="name" type="text" placeholder="name ..." v-model.trim="name">
            <input class="item" type="text" placeholder="type anything welcomed ..." v-model.trim="newTodoItem" v-on:keyup.enter="add_todo">
            <button @click="add_todo" class="btn btn-primary btn-sm">ADD</button>
        </div>
    
        <ul class="todoList">
            <li v-for="(todo, index) in todoItems">
                <span>{ todo.name }::: { todo.item } </span>
                <span class="removeBtn" @click="remove_todo(index)">&#x00D7</span>
            </li>
        </ul>

    </div>
{% endblock %}

{% block extra-script %}
    <script src="https://unpkg.com/vue/dist/vue.min.js"></script>
    <script>
        var vm = new Vue({
            delimiters: ['{', '}'],
            el: '#app',
            data: {
                name: '',
                newTodoItem: '',
                todoItems:[
                ],
            },
            methods: {
                add_todo: function() {
                    console.log("add_todo()...");
                    if (this.newTodoItem == '') return;
                    if (this.name == '') this.name = "김주회";

                    this.todoItems.push({name: this.name, item: this.newTodoItem});
                    this.clear_input();
                },
                remove_todo: function(index) {
                    console.log("remove_todo()...");
                    this.todoItems.splice(index, 1);
                },
                clear_input: function() {
                    this.name = '';
                    this.newTodoItem = '';
                }
            },
        })
    </script>
{% endblock %}